### ISSUE TITLE
Provide ZPL generation in a separate gem

### ISSUE THREAD

**Issue by TimSullivan** [bbulpett/zebra-zpl#12]
Using Heroku, I am unable to deploy this as it relies on CUPS, which Heroku doesn't (and, really, oughtn't) have installed. The ZPL generation is what I need, and I send that generated code to a print service.

Having a "ZebraPrint" gem that requires a "ZpLGenerate" gem would be great, allowing for both the integration you need, but allow for the ZPL functionality to be used separately.

**Comment by bbulpett** [comment]
Thanks for the suggestion. This gem was created to provide a means for direct, raw printing from an API to a client computer. For example, to print shipping labels at an industrial shipping station or sales receipts in a POS application. In most cases, this is being used in a UNIX environment either locally hosted or served in the cloud (Digital Ocean, Linode, AWS, etc) where one has the ability to add the requisite CUPS libraries. 

Understandably one would want to use this gem in a Heroku application, and while it's true that Heroku-CLI is somewhat restrictive, it seems that there should be some buildpack out there that includes CUPS support. If so, one would be able to capture the raw ZPL in transit instead of actually printing it. You might try to use `heroku run bash` (disclaimer - have not tried, won't be responsible for any issues) and see if you can install CUPS server library. It's just Ubuntu.

Alternatively, you can fork this gem and make a yourself a version that sends the ZPL to a file as you are needing. This would definitely be faster than waiting for us to create a separate gem as we are currently managing many other projects.

**Comment by TimSullivan** [comment]
Thanks for taking the time to reply! 😄 

Regarding forking: certainly; I did a quick and deeply, deeply dirty version for me to use straight away.  I was simply making a suggestion for the future. 🚀 

I'm basically using `label.dump_contents(zpl)` and then forwarding that generated zpl to our print servers in a raw form, which is exactly what I need.

**Comment by mtking2** [comment]
As of now, version 1.1.0 (and I think we may have even removed it on the published version of 1.0.5), CUPS is no longer a required dependency.
